modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="packofcharcoal" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Pack of Charcoal" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Michael T. Ross" #optional

(#mandatory)
description='''
This is a simple mod that adds a pack of charcoal item.

The recipe for this item is four charcoal in a 2x2 pattern. A pack of charcoal can be crafted back into four charcoal.

A pack of charcoal can be used as fuel for smelting. One pack of charcoal lasts 320 seconds (smelting up to 32 items), the same as the four charcoal used to craft it.
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
