modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT License"

[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="${mod_name}"
updateJSONURL="${git_repo}/update.json"
displayURL="${curse_homepage}"
logoFile="pack.png"
authors="${mod_author}"

description='''
A simple mod to add a pack of charcoal item and its recipe to Minecraft.

To craft a pack of charcoal, put four charcoal in a 2x2 square on a crafting grid.
A single pack of charcoal can be used to craft four charcoal, allowing for bulk storage of charcoal.

A pack of charcoal can be used as fuel for smelting.
A single pack of charcoal will smelt 32 items, equal to the four charcoal used to make it with no added efficiency.
'''

[[dependencies.packofcharcoal]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.packofcharcoal]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
