modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT License"

[[mods]]
modId="packofcharcoal"
version="${file.jarVersion}"
displayName="Pack of Charcoal"
updateJSONURL="https://github.com/MichaelTRoss0/Minecraft-Pack-of-Charcoal/update.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="pack.png"
authors="Michael T. Ross"

description='''
This is a simple mod that adds a pack of charcoal item.

The recipe for this item is four charcoal in a 2x2 pattern.
A pack of charcoal can be crafted back into four charcoal, allowing for bulk storage of charcoal.

A pack of charcoal can also be used as fuel for smelting.
One pack of charcoal lasts 320 seconds (smelting up to 32 items), the same as the four charcoal used to craft it.
'''

[[dependencies.packofcharcoal]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.packofcharcoal]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
