modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT License"

[[mods]]
modId="packofcharcoal"
version="${file.jarVersion}"
displayName="Pack of Charcoal"
updateJSONURL="https://github.com/MichaelTRoss0/Minecraft-Pack-of-Charcoal/update.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="pack.png"
authors="Michael T. Ross"

description='''
A simple mod to add a pack of charcoal item and its recipe to Minecraft.

To craft a pack of charcoal, put four charcoal in a 2x2 square on a crafting grid.
A single pack of charcoal can be used to craft four charcoal, allowing for bulk storage of charcoal.

A pack of charcoal can be used as fuel for smelting.
A single pack of charcoal will smelt 32 items, equal to the four charcoal used to make it with no added efficiency.
'''

[[dependencies.packofcharcoal]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.packofcharcoal]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
